"""Asset universe definitions for TradeBot v5.0."""

TOP_CRYPTO = [
    {"name": "Bitcoin", "symbol": "BTC", "yfinance": "BTC-USD", "coingecko": "bitcoin"},
    {"name": "Ethereum", "symbol": "ETH", "yfinance": "ETH-USD", "coingecko": "ethereum"},
    {"name": "Solana", "symbol": "SOL", "yfinance": "SOL-USD", "coingecko": "solana"},
    {"name": "BNB", "symbol": "BNB", "yfinance": "BNB-USD", "coingecko": "binancecoin"},
    {"name": "Cardano", "symbol": "ADA", "yfinance": "ADA-USD", "coingecko": "cardano"},
    {"name": "XRP", "symbol": "XRP", "yfinance": "XRP-USD", "coingecko": "ripple"},
    {"name": "Dogecoin", "symbol": "DOGE", "yfinance": "DOGE-USD", "coingecko": "dogecoin"},
    {"name": "Polkadot", "symbol": "DOT", "yfinance": "DOT-USD", "coingecko": "polkadot"},
    {"name": "Polygon", "symbol": "MATIC", "yfinance": "MATIC-USD", "coingecko": "matic-network"},
    {"name": "Avalanche", "symbol": "AVAX", "yfinance": "AVAX-USD", "coingecko": "avalanche-2"},
    {"name": "Litecoin", "symbol": "LTC", "yfinance": "LTC-USD", "coingecko": "litecoin"},
    {"name": "Chainlink", "symbol": "LINK", "yfinance": "LINK-USD", "coingecko": "chainlink"},
    {"name": "Stellar", "symbol": "XLM", "yfinance": "XLM-USD", "coingecko": "stellar"},
    {"name": "Uniswap", "symbol": "UNI", "yfinance": "UNI-USD", "coingecko": "uniswap"},
    {"name": "Cosmos", "symbol": "ATOM", "yfinance": "ATOM-USD", "coingecko": "cosmos"},
    {"name": "Filecoin", "symbol": "FIL", "yfinance": "FIL-USD", "coingecko": "filecoin"},
    {"name": "Internet Computer", "symbol": "ICP", "yfinance": "ICP-USD", "coingecko": "internet-computer"},
    {"name": "Aave", "symbol": "AAVE", "yfinance": "AAVE-USD", "coingecko": "aave"},
    {"name": "Algorand", "symbol": "ALGO", "yfinance": "ALGO-USD", "coingecko": "algorand"},
    {"name": "Tezos", "symbol": "XTZ", "yfinance": "XTZ-USD", "coingecko": "tezos"},
    {"name": "VeChain", "symbol": "VET", "yfinance": "VET-USD", "coingecko": "vechain"},
    {"name": "THORChain", "symbol": "RUNE", "yfinance": "RUNE-USD", "coingecko": "thorchain"},
    {"name": "Near Protocol", "symbol": "NEAR", "yfinance": "NEAR-USD", "coingecko": "near"},
    {"name": "Monero", "symbol": "XMR", "yfinance": "XMR-USD", "coingecko": "monero"},
    {"name": "Aptos", "symbol": "APT", "yfinance": "APT-USD", "coingecko": "aptos"},
    {"name": "Quant", "symbol": "QNT", "yfinance": "QNT-USD", "coingecko": "quant-network"},
    {"name": "Hedera", "symbol": "HBAR", "yfinance": "HBAR-USD", "coingecko": "hedera-hashgraph"},
    {"name": "Maker", "symbol": "MKR", "yfinance": "MKR-USD", "coingecko": "maker"},
    {"name": "Arbitrum", "symbol": "ARB", "yfinance": "ARB-USD", "coingecko": "arbitrum"},
    {"name": "Optimism", "symbol": "OP", "yfinance": "OP-USD", "coingecko": "optimism"},
    {"name": "Sui", "symbol": "SUI", "yfinance": "SUI-USD", "coingecko": "sui"},
    {"name": "Curve DAO", "symbol": "CRV", "yfinance": "CRV-USD", "coingecko": "curve-dao-token"},
    {"name": "BitTorrent", "symbol": "BTT", "yfinance": "BTT-USD", "coingecko": "bittorrent"},
    {"name": "Immutable", "symbol": "IMX", "yfinance": "IMX-USD", "coingecko": "immutable-x"},
    {"name": "Render", "symbol": "RNDR", "yfinance": "RNDR-USD", "coingecko": "render-token"},
    {"name": "The Graph", "symbol": "GRT", "yfinance": "GRT-USD", "coingecko": "the-graph"},
    {"name": "Axie Infinity", "symbol": "AXS", "yfinance": "AXS-USD", "coingecko": "axie-infinity"},
    {"name": "dYdX", "symbol": "DYDX", "yfinance": "DYDX-USD", "coingecko": "dydx"},
    {"name": "Kava", "symbol": "KAVA", "yfinance": "KAVA-USD", "coingecko": "kava"},
    {"name": "Fantom", "symbol": "FTM", "yfinance": "FTM-USD", "coingecko": "fantom"},
    {"name": "Gala", "symbol": "GALA", "yfinance": "GALA-USD", "coingecko": "gala"},
    {"name": "Flow", "symbol": "FLOW", "yfinance": "FLOW-USD", "coingecko": "flow"},
    {"name": "Stacks", "symbol": "STX", "yfinance": "STX-USD", "coingecko": "blockstack"},
    {"name": "Injective", "symbol": "INJ", "yfinance": "INJ-USD", "coingecko": "injective-protocol"},
    {"name": "ThorChain", "symbol": "RUNE", "yfinance": "RUNE-USD", "coingecko": "thorchain"},
    {"name": "Zcash", "symbol": "ZEC", "yfinance": "ZEC-USD", "coingecko": "zcash"},
    {"name": "Kaspa", "symbol": "KAS", "yfinance": "KAS-USD", "coingecko": "kaspa"},
    {"name": "Celestia", "symbol": "TIA", "yfinance": "TIA-USD", "coingecko": "celestia"},
    {"name": "Bonk", "symbol": "BONK", "yfinance": "BONK-USD", "coingecko": "bonk"},
    {"name": "Worldcoin", "symbol": "WLD", "yfinance": "WLD-USD", "coingecko": "worldcoin-wld"},
    {"name": "Pepe", "symbol": "PEPE", "yfinance": "PEPE-USD", "coingecko": "pepe"}
]

TOP_STOCKS = [
    "AAPL", "MSFT", "AMZN", "GOOGL", "GOOG", "META", "NVDA", "BRK-B", "UNH", "V",
    "XOM", "JPM", "LLY", "JNJ", "TSLA", "AVGO", "HD", "PG", "MA", "CVX",
    "MRK", "ABBV", "PEP", "COST", "KO", "BAC", "PFE", "ADBE", "TMO", "CSCO",
    "WMT", "ACN", "MCD", "DHR", "ABT", "NFLX", "CRM", "LIN", "NKE", "AMD",
    "NEE", "TXN", "PM", "UPS", "BMY", "QCOM", "SCHW", "AMGN", "HON", "IBM",
    "SBUX", "RTX", "LOW", "ORCL", "CVS", "CAT", "SPGI", "MS", "GS", "INTU",
    "PLD", "BLK", "MDLZ", "GE", "T", "ISRG", "AMT", "C", "LMT", "INTC",
    "DE", "SYK", "ADP", "TJX", "MO", "ELV", "NOW", "GILD", "MDT", "BKNG",
    "PYPL", "BA", "USB", "FIS", "TGT", "MMC", "ADI", "ZTS", "CI", "SO",
    "SHW", "CME", "PNC", "DUK", "BDX", "EW", "CL", "AXP", "FDX", "DAL"
]
"""This module exposes the top 50 cryptocurrency and top 100 stock tickers for screening."""
