import { CheckCircle, Award, Shield, BookOpen } from 'lucide-react';

export const metadata = {
  title: 'About MyIrishTax - ACCA Qualified Irish Tax Calculators',
  description:
    'MyIrishTax is built by Aleksander Canchaya, an ACCA qualified accountant with 13+ years experience. Free, accurate Irish tax calculators for PAYE, USC, PRSI, contractors, rental income, and more.',
};

export default function AboutPage() {
  return (
    <main className="mx-auto max-w-6xl px-4 py-10">
      {/* Header */}
      <header className="rounded-xl bg-white border border-gray-200 shadow-sm p-8 mb-6">
        <h1 className="text-4xl font-bold text-gray-900">About MyIrishTax</h1>
        <p className="mt-3 text-lg text-gray-600 max-w-2xl">
          Free, accurate Irish tax calculators — built by a qualified accountant, not an algorithm.
        </p>
      </header>

      <div className="space-y-6">
        {/* About the Founder */}
        <section className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <Award className="h-6 w-6 text-brand-600 flex-shrink-0" />
            <h2 className="text-2xl font-semibold text-gray-900">About the Founder</h2>
          </div>
          <div className="space-y-4 text-gray-700 leading-relaxed">
            <p>
              <span className="font-semibold text-gray-900">Aleksander Canchaya</span> is an ACCA
              Qualified Accountant (Member of the Association of Chartered Certified Accountants)
              with over 13 years of professional accounting and tax experience.
            </p>
            <p>
              Aleksander currently serves as a Global RTR Intercompany Leader at a multinational
              corporation, managing the record-to-report function across 52 entities in the EMEA
              region. This role demands deep expertise in international accounting standards,
              multi-jurisdiction tax compliance, and financial controls at scale.
            </p>
            <p>
              Aleksander founded MyIrishTax to make Irish tax calculations accessible to everyone.
              With over 13 years of professional accounting experience and ACCA qualification, he
              brings deep expertise in Irish tax law, international accounting standards, and
              financial planning. His work managing complex multi-entity operations across Europe
              gives him a unique perspective on tax efficiency and compliance.
            </p>
          </div>
        </section>

        {/* Why MyIrishTax */}
        <section className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <CheckCircle className="h-6 w-6 text-brand-600 flex-shrink-0" />
            <h2 className="text-2xl font-semibold text-gray-900">Why MyIrishTax</h2>
          </div>
          <ul className="space-y-4">
            <li className="flex items-start gap-3">
              <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold text-gray-900">Built by a qualified accountant.</span>
                <span className="text-gray-600">
                  {' '}Every calculator on this site is designed and verified by an ACCA-qualified professional — not generated by a generic tool.
                </span>
              </div>
            </li>
            <li className="flex items-start gap-3">
              <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold text-gray-900">Updated annually with Budget changes.</span>
                <span className="text-gray-600">
                  {' '}Tax bands, credits, USC rates, and PRSI thresholds are reviewed and updated each year following the Irish Budget to keep calculations accurate.
                </span>
              </div>
            </li>
            <li className="flex items-start gap-3">
              <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold text-gray-900">Based on current Revenue rules.</span>
                <span className="text-gray-600">
                  {' '}Calculations follow actual Revenue.ie rules — not generic estimates. PAYE, USC, PRSI, CGT, and rental income are all computed to the current rules.
                </span>
              </div>
            </li>
            <li className="flex items-start gap-3">
              <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0 mt-0.5" />
              <div>
                <span className="font-semibold text-gray-900">Privacy-first.</span>
                <span className="text-gray-600">
                  {' '}No tracking pixels, no selling your data. Your income figures stay on your device.
                </span>
              </div>
            </li>
          </ul>
        </section>

        {/* Qualifications & Credentials */}
        <section className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <BookOpen className="h-6 w-6 text-brand-600 flex-shrink-0" />
            <h2 className="text-2xl font-semibold text-gray-900">Qualifications &amp; Credentials</h2>
          </div>
          <div className="space-y-4">
            <div>
              <h3 className="font-semibold text-gray-900 text-lg">
                ACCA — Association of Chartered Certified Accountants
              </h3>
              <p className="text-gray-600 mt-1 leading-relaxed">
                ACCA is one of the world's most respected professional accounting bodies, with over
                240,000 members and 542,000 students across 178 countries. ACCA members are
                required to meet rigorous examination, practical experience, and continuing
                professional development standards. The qualification is recognised by employers,
                regulators, and governments globally as a mark of accounting excellence.
              </p>
            </div>
            <div>
              <h3 className="font-semibold text-gray-900 text-base mb-2">Areas of expertise</h3>
              <div className="flex flex-wrap gap-2">
                {[
                  'Irish Income Tax',
                  'USC (Universal Social Charge)',
                  'PRSI',
                  'Capital Gains Tax',
                  'Rental Income Tax',
                  'Contractor Tax (IT8 / S.481)',
                  'Auto-Enrolment / Pension Planning',
                  'International Accounting Standards',
                  'Multi-Entity Tax Compliance',
                ].map((area) => (
                  <span
                    key={area}
                    className="inline-block rounded-full border border-gray-200 bg-gray-50 px-3 py-1 text-sm text-gray-700"
                  >
                    {area}
                  </span>
                ))}
              </div>
            </div>
          </div>
        </section>

        {/* Disclaimer */}
        <section className="rounded-xl border border-gray-200 bg-white p-6 shadow-sm">
          <div className="flex items-center gap-3 mb-4">
            <Shield className="h-6 w-6 text-brand-600 flex-shrink-0" />
            <h2 className="text-2xl font-semibold text-gray-900">Disclaimer</h2>
          </div>
          <p className="text-gray-600 leading-relaxed">
            The calculators on MyIrishTax are provided for informational purposes only and should
            not be considered professional tax advice. While we strive for accuracy, tax laws change
            frequently. For personalised advice on your specific tax situation, consult a qualified
            tax advisor or accountant. MyIrishTax is not responsible for any decisions made based
            on calculations from this site.
          </p>
        </section>
      </div>
    </main>
  );
}
